### ISSUE TITLE
Create Lucky Action Integration

### ISSUE THREAD

**Issue by grepsedawk** [the-business-factory/slack.cr#1]
`class Api::SlackEvents::Create < ApiAction`
Using the ApiAction here is expecting all of the Jwt auth stuff (which you do skip in your example)
Instead, I think it would be better to make your own "base action" to inherit from.

It could include:
``` 
post "/api/slack_events" do
    if challenge = params.get?(:challenge)
      json({challenge: challenge})
    else
      process_webhook_data!
      json({ok: true})
    end
  end

  private def process_webhook_data!
    verified_event = Slack::VerifiedEvent.from_request(event).event
    handle_event(verified_event)
  end
```
as well

**Comment by robcole** [comment]
Done, thanks for the idea!
